// Code generated by entc, DO NOT EDIT.

package ent

import (
	"bongo/ent/predicate"
	"bongo/ent/sellerrequest"
	"bongo/ent/shopcategory"
	"bongo/ent/user"
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SellerRequestQuery is the builder for querying SellerRequest entities.
type SellerRequestQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.SellerRequest
	// eager-loading edges.
	withShopCategory *ShopCategoryQuery
	withUser         *UserQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SellerRequestQuery builder.
func (srq *SellerRequestQuery) Where(ps ...predicate.SellerRequest) *SellerRequestQuery {
	srq.predicates = append(srq.predicates, ps...)
	return srq
}

// Limit adds a limit step to the query.
func (srq *SellerRequestQuery) Limit(limit int) *SellerRequestQuery {
	srq.limit = &limit
	return srq
}

// Offset adds an offset step to the query.
func (srq *SellerRequestQuery) Offset(offset int) *SellerRequestQuery {
	srq.offset = &offset
	return srq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (srq *SellerRequestQuery) Unique(unique bool) *SellerRequestQuery {
	srq.unique = &unique
	return srq
}

// Order adds an order step to the query.
func (srq *SellerRequestQuery) Order(o ...OrderFunc) *SellerRequestQuery {
	srq.order = append(srq.order, o...)
	return srq
}

// QueryShopCategory chains the current query on the "shop_category" edge.
func (srq *SellerRequestQuery) QueryShopCategory() *ShopCategoryQuery {
	query := &ShopCategoryQuery{config: srq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := srq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := srq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sellerrequest.Table, sellerrequest.FieldID, selector),
			sqlgraph.To(shopcategory.Table, shopcategory.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sellerrequest.ShopCategoryTable, sellerrequest.ShopCategoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(srq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (srq *SellerRequestQuery) QueryUser() *UserQuery {
	query := &UserQuery{config: srq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := srq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := srq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sellerrequest.Table, sellerrequest.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sellerrequest.UserTable, sellerrequest.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(srq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SellerRequest entity from the query.
// Returns a *NotFoundError when no SellerRequest was found.
func (srq *SellerRequestQuery) First(ctx context.Context) (*SellerRequest, error) {
	nodes, err := srq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sellerrequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (srq *SellerRequestQuery) FirstX(ctx context.Context) *SellerRequest {
	node, err := srq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SellerRequest ID from the query.
// Returns a *NotFoundError when no SellerRequest ID was found.
func (srq *SellerRequestQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = srq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sellerrequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (srq *SellerRequestQuery) FirstIDX(ctx context.Context) int {
	id, err := srq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SellerRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one SellerRequest entity is not found.
// Returns a *NotFoundError when no SellerRequest entities are found.
func (srq *SellerRequestQuery) Only(ctx context.Context) (*SellerRequest, error) {
	nodes, err := srq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sellerrequest.Label}
	default:
		return nil, &NotSingularError{sellerrequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (srq *SellerRequestQuery) OnlyX(ctx context.Context) *SellerRequest {
	node, err := srq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SellerRequest ID in the query.
// Returns a *NotSingularError when exactly one SellerRequest ID is not found.
// Returns a *NotFoundError when no entities are found.
func (srq *SellerRequestQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = srq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sellerrequest.Label}
	default:
		err = &NotSingularError{sellerrequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (srq *SellerRequestQuery) OnlyIDX(ctx context.Context) int {
	id, err := srq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SellerRequests.
func (srq *SellerRequestQuery) All(ctx context.Context) ([]*SellerRequest, error) {
	if err := srq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return srq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (srq *SellerRequestQuery) AllX(ctx context.Context) []*SellerRequest {
	nodes, err := srq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SellerRequest IDs.
func (srq *SellerRequestQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := srq.Select(sellerrequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (srq *SellerRequestQuery) IDsX(ctx context.Context) []int {
	ids, err := srq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (srq *SellerRequestQuery) Count(ctx context.Context) (int, error) {
	if err := srq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return srq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (srq *SellerRequestQuery) CountX(ctx context.Context) int {
	count, err := srq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (srq *SellerRequestQuery) Exist(ctx context.Context) (bool, error) {
	if err := srq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return srq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (srq *SellerRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := srq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SellerRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (srq *SellerRequestQuery) Clone() *SellerRequestQuery {
	if srq == nil {
		return nil
	}
	return &SellerRequestQuery{
		config:           srq.config,
		limit:            srq.limit,
		offset:           srq.offset,
		order:            append([]OrderFunc{}, srq.order...),
		predicates:       append([]predicate.SellerRequest{}, srq.predicates...),
		withShopCategory: srq.withShopCategory.Clone(),
		withUser:         srq.withUser.Clone(),
		// clone intermediate query.
		sql:  srq.sql.Clone(),
		path: srq.path,
	}
}

// WithShopCategory tells the query-builder to eager-load the nodes that are connected to
// the "shop_category" edge. The optional arguments are used to configure the query builder of the edge.
func (srq *SellerRequestQuery) WithShopCategory(opts ...func(*ShopCategoryQuery)) *SellerRequestQuery {
	query := &ShopCategoryQuery{config: srq.config}
	for _, opt := range opts {
		opt(query)
	}
	srq.withShopCategory = query
	return srq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (srq *SellerRequestQuery) WithUser(opts ...func(*UserQuery)) *SellerRequestQuery {
	query := &UserQuery{config: srq.config}
	for _, opt := range opts {
		opt(query)
	}
	srq.withUser = query
	return srq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SellerName string `json:"seller_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SellerRequest.Query().
//		GroupBy(sellerrequest.FieldSellerName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (srq *SellerRequestQuery) GroupBy(field string, fields ...string) *SellerRequestGroupBy {
	group := &SellerRequestGroupBy{config: srq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := srq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return srq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SellerName string `json:"seller_name,omitempty"`
//	}
//
//	client.SellerRequest.Query().
//		Select(sellerrequest.FieldSellerName).
//		Scan(ctx, &v)
//
func (srq *SellerRequestQuery) Select(fields ...string) *SellerRequestSelect {
	srq.fields = append(srq.fields, fields...)
	return &SellerRequestSelect{SellerRequestQuery: srq}
}

func (srq *SellerRequestQuery) prepareQuery(ctx context.Context) error {
	for _, f := range srq.fields {
		if !sellerrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if srq.path != nil {
		prev, err := srq.path(ctx)
		if err != nil {
			return err
		}
		srq.sql = prev
	}
	return nil
}

func (srq *SellerRequestQuery) sqlAll(ctx context.Context) ([]*SellerRequest, error) {
	var (
		nodes       = []*SellerRequest{}
		withFKs     = srq.withFKs
		_spec       = srq.querySpec()
		loadedTypes = [2]bool{
			srq.withShopCategory != nil,
			srq.withUser != nil,
		}
	)
	if srq.withShopCategory != nil || srq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, sellerrequest.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &SellerRequest{config: srq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, srq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := srq.withShopCategory; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*SellerRequest)
		for i := range nodes {
			if nodes[i].shop_category_seller_requests == nil {
				continue
			}
			fk := *nodes[i].shop_category_seller_requests
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(shopcategory.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "shop_category_seller_requests" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.ShopCategory = n
			}
		}
	}

	if query := srq.withUser; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*SellerRequest)
		for i := range nodes {
			if nodes[i].user_seller_requests == nil {
				continue
			}
			fk := *nodes[i].user_seller_requests
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_seller_requests" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.User = n
			}
		}
	}

	return nodes, nil
}

func (srq *SellerRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := srq.querySpec()
	return sqlgraph.CountNodes(ctx, srq.driver, _spec)
}

func (srq *SellerRequestQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := srq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (srq *SellerRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sellerrequest.Table,
			Columns: sellerrequest.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sellerrequest.FieldID,
			},
		},
		From:   srq.sql,
		Unique: true,
	}
	if unique := srq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := srq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sellerrequest.FieldID)
		for i := range fields {
			if fields[i] != sellerrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := srq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := srq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := srq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := srq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (srq *SellerRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(srq.driver.Dialect())
	t1 := builder.Table(sellerrequest.Table)
	columns := srq.fields
	if len(columns) == 0 {
		columns = sellerrequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if srq.sql != nil {
		selector = srq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range srq.predicates {
		p(selector)
	}
	for _, p := range srq.order {
		p(selector)
	}
	if offset := srq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := srq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SellerRequestGroupBy is the group-by builder for SellerRequest entities.
type SellerRequestGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (srgb *SellerRequestGroupBy) Aggregate(fns ...AggregateFunc) *SellerRequestGroupBy {
	srgb.fns = append(srgb.fns, fns...)
	return srgb
}

// Scan applies the group-by query and scans the result into the given value.
func (srgb *SellerRequestGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := srgb.path(ctx)
	if err != nil {
		return err
	}
	srgb.sql = query
	return srgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (srgb *SellerRequestGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := srgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (srgb *SellerRequestGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(srgb.fields) > 1 {
		return nil, errors.New("ent: SellerRequestGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := srgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (srgb *SellerRequestGroupBy) StringsX(ctx context.Context) []string {
	v, err := srgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (srgb *SellerRequestGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = srgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sellerrequest.Label}
	default:
		err = fmt.Errorf("ent: SellerRequestGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (srgb *SellerRequestGroupBy) StringX(ctx context.Context) string {
	v, err := srgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (srgb *SellerRequestGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(srgb.fields) > 1 {
		return nil, errors.New("ent: SellerRequestGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := srgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (srgb *SellerRequestGroupBy) IntsX(ctx context.Context) []int {
	v, err := srgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (srgb *SellerRequestGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = srgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sellerrequest.Label}
	default:
		err = fmt.Errorf("ent: SellerRequestGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (srgb *SellerRequestGroupBy) IntX(ctx context.Context) int {
	v, err := srgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (srgb *SellerRequestGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(srgb.fields) > 1 {
		return nil, errors.New("ent: SellerRequestGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := srgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (srgb *SellerRequestGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := srgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (srgb *SellerRequestGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = srgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sellerrequest.Label}
	default:
		err = fmt.Errorf("ent: SellerRequestGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (srgb *SellerRequestGroupBy) Float64X(ctx context.Context) float64 {
	v, err := srgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (srgb *SellerRequestGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(srgb.fields) > 1 {
		return nil, errors.New("ent: SellerRequestGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := srgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (srgb *SellerRequestGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := srgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (srgb *SellerRequestGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = srgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sellerrequest.Label}
	default:
		err = fmt.Errorf("ent: SellerRequestGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (srgb *SellerRequestGroupBy) BoolX(ctx context.Context) bool {
	v, err := srgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (srgb *SellerRequestGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range srgb.fields {
		if !sellerrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := srgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := srgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (srgb *SellerRequestGroupBy) sqlQuery() *sql.Selector {
	selector := srgb.sql.Select()
	aggregation := make([]string, 0, len(srgb.fns))
	for _, fn := range srgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(srgb.fields)+len(srgb.fns))
		for _, f := range srgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(srgb.fields...)...)
}

// SellerRequestSelect is the builder for selecting fields of SellerRequest entities.
type SellerRequestSelect struct {
	*SellerRequestQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (srs *SellerRequestSelect) Scan(ctx context.Context, v interface{}) error {
	if err := srs.prepareQuery(ctx); err != nil {
		return err
	}
	srs.sql = srs.SellerRequestQuery.sqlQuery(ctx)
	return srs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (srs *SellerRequestSelect) ScanX(ctx context.Context, v interface{}) {
	if err := srs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (srs *SellerRequestSelect) Strings(ctx context.Context) ([]string, error) {
	if len(srs.fields) > 1 {
		return nil, errors.New("ent: SellerRequestSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := srs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (srs *SellerRequestSelect) StringsX(ctx context.Context) []string {
	v, err := srs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (srs *SellerRequestSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = srs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sellerrequest.Label}
	default:
		err = fmt.Errorf("ent: SellerRequestSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (srs *SellerRequestSelect) StringX(ctx context.Context) string {
	v, err := srs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (srs *SellerRequestSelect) Ints(ctx context.Context) ([]int, error) {
	if len(srs.fields) > 1 {
		return nil, errors.New("ent: SellerRequestSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := srs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (srs *SellerRequestSelect) IntsX(ctx context.Context) []int {
	v, err := srs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (srs *SellerRequestSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = srs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sellerrequest.Label}
	default:
		err = fmt.Errorf("ent: SellerRequestSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (srs *SellerRequestSelect) IntX(ctx context.Context) int {
	v, err := srs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (srs *SellerRequestSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(srs.fields) > 1 {
		return nil, errors.New("ent: SellerRequestSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := srs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (srs *SellerRequestSelect) Float64sX(ctx context.Context) []float64 {
	v, err := srs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (srs *SellerRequestSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = srs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sellerrequest.Label}
	default:
		err = fmt.Errorf("ent: SellerRequestSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (srs *SellerRequestSelect) Float64X(ctx context.Context) float64 {
	v, err := srs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (srs *SellerRequestSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(srs.fields) > 1 {
		return nil, errors.New("ent: SellerRequestSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := srs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (srs *SellerRequestSelect) BoolsX(ctx context.Context) []bool {
	v, err := srs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (srs *SellerRequestSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = srs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{sellerrequest.Label}
	default:
		err = fmt.Errorf("ent: SellerRequestSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (srs *SellerRequestSelect) BoolX(ctx context.Context) bool {
	v, err := srs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (srs *SellerRequestSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := srs.sql.Query()
	if err := srs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
